---
#file: roles/dre/tasks/main.yml

- name: Make node group
  group: name=node system=yes state=present

- name: Make node user
  user: name=node group=node system=yes state=present

- name: Make DRE folder
  command: mkdir -p "/var/www/dre"

- name: Make source folder
  command: mkdir -p "/var/www/dre/source"

- name: Make shared folder
  command: mkdir -p "/var/www/dre/shared"

- name: Make current folder
  command: mkdir -p "/var/www/dre/current"

- name: Clone DRE repository
  git: repo="https://github.com/amida-tech/DRE.git" dest="/var/www/dre/source" #version="v1.3.1"

- name: Copy DRE source to current
  command: cp -r /var/www/dre/source/. /var/www/dre/current

- name:  Install grunt CLI tools
  sudo: yes
  command: npm install -g grunt-cli

- name:  Install bower CLI tools
  sudo: yes
  command: npm install -g bower

- name: install libxml2
  yum: name=libxml2 state="latest"
  sudo: yes

- name:  Install node-gyp
  sudo: yes
  command: npm install -g node-gyp

#- name:  Install DRE client dependencies
#  command: npm install chdir=/var/www/dre/current/client 

- name:  Install DRE client bower dependencies
  command: bower install --allow-root chdir=/var/www/dre/current


#- name: Install ruby
#  yum: name={{item}} enablerepo="epel" state="latest"
#  sudo: yes
#  with_items:
#    - ruby
#    - ruby-devel 
#    - rubygems

#- name:  Update ruby gems
#  command: gem update --system
#  sudo: yes

#- name:  Install Compass gem
#  command: gem install compass
#  sudo: yes

#- name:  Run client build
#  command: grunt dev chdir=/var/www/dre/current/client



- name:  Install DRE server dependencies
  command: npm install --production chdir=/var/www/dre/current
  sudo: yes 

- name:  Install PM2
  command: npm install -g pm2 --unsafe-perm
  
- name: Launch DRE through PM2
  command: pm2 start /var/www/dre/current/server.js
  
- name:  Configure PM2 for Auto-reload
  sudo: yes
  command: pm2 startup centos -u node && pm2 save

